# Generated by Django 5.2.5 on 2025-10-24 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date_pub', models.DateField(auto_now_add=True)),
                ('lien', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('adresse', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FaqSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Forfait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description1', models.CharField(blank=True, max_length=255)),
                ('description2', models.CharField(blank=True, max_length=255)),
                ('description3', models.CharField(blank=True, max_length=255)),
                ('description4', models.CharField(blank=True, max_length=255)),
                ('prix', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Prix (GNF)')),
                ('icone', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='forfaits/')),
                ('type', models.CharField(choices=[('FO', 'Fibre Optique'), ('FH', 'Faisceau Hertzien')], default='FO', max_length=10)),
                ('is_bon_plan', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='logo/')),
                ('alt', models.CharField(default='Logo SkyConnect', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MessageContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('sujet', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('date_envoye', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('icone', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='produits/')),
                ('is_bon_plan', models.BooleanField(default=False)),
                ('quantite', models.PositiveIntegerField(default=0, verbose_name='Quantité en stock')),
                ('caracteristiques', models.TextField(blank=True, help_text='Caractéristiques techniques ou points forts du produit')),
                ('reference', models.CharField(blank=True, help_text='Référence ou SKU du produit', max_length=100)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuickBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='quickblocks/')),
                ('url_name', models.CharField(help_text="Nom de l'URL Django (ex: 'forfaits', 'faq')", max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('extra_description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, help_text="Classe Bootstrap Icons (ex: 'bi-box-seam')", max_length=50)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='sliders/')),
                ('is_active', models.BooleanField(default=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ZoneCouverture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActualiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog/')),
                ('alt', models.CharField(blank=True, max_length=100)),
                ('actualite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.actualite')),
            ],
        ),
        migrations.CreateModel(
            name='FaqImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='faq/')),
                ('legend', models.CharField(blank=True, max_length=255)),
                ('faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.faq')),
            ],
        ),
        migrations.AddField(
            model_name='faq',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='core.faqsection'),
        ),
        migrations.CreateModel(
            name='FaqStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.faq')),
            ],
        ),
        migrations.CreateModel(
            name='FaqStepImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='faq_steps/')),
                ('legend', models.CharField(blank=True, max_length=255)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.faqstep')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=12, unique=True)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmée'), ('en_preparation', 'En préparation'), ('pret', 'Prêt pour retrait'), ('livre', 'Livrée'), ('annule', 'Annulée')], default='en_attente', max_length=20)),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('mode_reception', models.CharField(choices=[('agence', 'Retrait en agence'), ('livraison', 'Livraison à domicile')], max_length=20)),
                ('adresse_livraison', models.TextField(blank=True, null=True)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('agence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.agence')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.commune')),
            ],
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PanierItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.panier')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produit')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_ligne', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produit')),
            ],
        ),
        migrations.CreateModel(
            name='SousCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_categories', to='core.categorie')),
            ],
        ),
        migrations.AddField(
            model_name='produit',
            name='sous_categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='core.souscategorie'),
        ),
        migrations.CreateModel(
            name='DemandeSouscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.commune')),
                ('forfait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.forfait')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.zonecouverture')),
            ],
        ),
        migrations.AddField(
            model_name='commune',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communes', to='core.zonecouverture'),
        ),
    ]
