# Generated by Django 5.2.5 on 2025-10-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_logo_actif_alter_logo_alt_alter_logo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agence',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='agence',
            name='longitude',
        ),
        migrations.AddField(
            model_name='agence',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='agence',
            name='telephone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agence',
            name='adresse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agence',
            name='nom',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
