# Generated by Django 5.2.8 on 2026-01-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_emailverificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='taux_tva',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Taux TVA (%)'),
        ),
        migrations.DeleteModel(
            name='EmailVerificationCode',
        ),
    ]
