# Generated by Django 5.2.8 on 2026-01-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_produit_taux_tva_delete_emailverificationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='taux_tva',
            field=models.DecimalField(decimal_places=2, default=18.0, max_digits=5, verbose_name='Taux TVA (%)'),
        ),
    ]
