# Generated by Django 5.2.8 on 2026-01-12 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_produit_taux_tva'),
    ]

    operations = [
        migrations.CreateModel(
            name='WifiTicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: 1 heure, 2 heures, 1 jour', max_length=100)),
                ('duree_heures', models.PositiveIntegerField(help_text='Durée en heures')),
                ('prix', models.DecimalField(decimal_places=2, help_text='Prix en GNF', max_digits=10)),
                ('description', models.TextField(blank=True, help_text='Description optionnelle')),
                ('is_active', models.BooleanField(default=True)),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Type de ticket WiFi',
                'verbose_name_plural': 'Types de tickets WiFi',
                'ordering': ['ordre', 'duree_heures'],
            },
        ),
        migrations.CreateModel(
            name='WifiTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(help_text='Identifiant de connexion', max_length=20, unique=True)),
                ('mot_de_passe', models.CharField(help_text='Mot de passe de connexion', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('date_utilisation', models.DateTimeField(blank=True, null=True)),
                ('hotspot', models.CharField(blank=True, help_text='Nom du hotspot utilisé', max_length=100)),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.wifitickettype')),
            ],
            options={
                'verbose_name': 'Ticket WiFi',
                'verbose_name_plural': 'Tickets WiFi',
                'ordering': ['-date_creation'],
            },
        ),
    ]
